apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-downloader
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: hf-downloader
  template:
    metadata:
      labels:
        app: hf-downloader
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc
